language: php

php:
  - 5.3
before_script:
    - yes | pecl install solr-beta
    - echo "extension=solr.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar install --dev
notifications:
  email:
    - fsemm.travis-ci@gmx.de    
